accounts/urls.py
from django.urls import path, include

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("delete/", views.delete, name="user_delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("randomQuestion/", include("randomQuestion.urls")),
]

randomQuestion/urls.py
from django.urls import path, include

# from .views import

app_name = "randomQuestion"

urlpatterns = [
    # path("register", RegistrationAPIView.as_view(), name="register"),
]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

randomQuestion/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ("email",)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout


def index(request):
    user = get_user_model().objects.get(pk=request.user.pk)  # 로그인 한 유저
    context = {
        "user": user,
    }
    return render(request, "accounts/index.html", context)


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)  # 회원가입과 동시에 로그인을 시키기 위해
            return redirect("accounts:index")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.user.is_authenticated:  # 로그인이 된 상태에서는 로그인 화면에 들어갈 수 없다.
        return redirect("accounts:index")
    if request.method == "POST":
        form = AuthenticationForm(
            request, data=request.POST
        )  # request가 없어도 잘 돌아가는거 같음 하지만 대부분이 request를 필수적으로 받아 가지고 편의상 넣겠음
        if form.is_valid():
            auth_login(request, form.get_user())  # login을 가져와야 한다.
            return redirect(
                request.GET.get("next") or "accounts:index"
            )  # login_required를 사용하기 위해
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("accounts:login")


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/detail.html", context)


def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("accounts:login")


def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:index")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context=context)


from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/change_password.html", context)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

  <h1>비밀번호 수정</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-outline-dark">수정</button>
    <button type="button" class="btn btn-outline-dark" onclick="location.href='{% url 'accounts:index' %}' ">돌아가기</button>
  </form>
{% endblock content %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>상세 회원 정보</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">user</th>
        <th scope="col">email</th>
        <th scope="col">last_login</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">{{ user.username}}</th>
        <td>{{ user.email}}</td>
        <td>{{ user.last_login}}</td>
      </tr>
    </tbody>
  </table>
  <button type="button" class="btn btn-outline-dark" onclick="location.href='{% url 'accounts:index' %}' ">돌아가기</button>
{% endblock content %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>{{ user.username}}님 환영합니다.</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">user</th>
        <th scope="col">email</th>
        <th scope="col">last_login</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">
          <a href="{% url 'accounts:detail' user.pk %}">{{ user.username}}</a>
        </th>
        <td>{{ user.email}}</td>
        <td>{{ user.last_login}}</td>
      </tr>
    </tbody>
  </table>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>login</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-outline-dark" onclick="location.href='{% url 'accounts:index' %}' ">로그인</button>
  </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

  <h1>signUp</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-outline-dark">제출</button>
  </form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

  <h1>update</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="제출"/>
    <button type="button" class="btn btn-outline-dark" onclick="location.href='{% url 'accounts:index' %}' ">돌아가기</button>
  </form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load django_bootstrap5 %}
{% load static %}
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    {% bootstrap_css%}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>
      {% block title %}{% endblock title %}
    </title>
  </head>

  <body>
    <header>
      <nav class="navbar  navbar-expand-md  navbar-dark bg-dark">
        <div>
          <a href="" class="navbar-brand ms-3">
            <span class=" material-symbols-outlined logo-icon">
              <i class="bi bi-easel2-fill"></i>
              Art Gallery
            </span>
          </a>
        </div>
        <div class="container">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
              {% if request.user.is_authenticated%}
                <li class="nav-item">
                  {% comment %} <a href="{% url 'reviews:index' %}" class="nav-link">게시판</a> {% endcomment %}
                </li>
                <li>
                  {% comment %} <a href="{% url 'accounts:profile'  %}" class='nav-link'>내 프로필 바로 가기</a> {% endcomment %}
                </li>
                <li class="nav-item">
                  <a class='nav-link' href="{% url 'accounts:logout' %}">
                    로그아웃
                  </a>
                </li>
              {% else %}
                <li>
                  <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
                </li>
                <li>
                  <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="container mt-3">
        {% block content %}{% endblock content %}
      </div>
    </main>

    {% bootstrap_javascript %}
    {% block script %}{% endblock script %}
  </body>

</html>